fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": 'git://github.com/cprice-puppet/puppetlabs-inifile'
    "postgresql": "git://github.com/puppetlabs/puppet-postgresql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apache": "git://github.com/puppetlabs/puppetlabs-apache.git"
    "concat": "git://github.com/ripienaar/puppet-concat.git"
    "firewall": "git://github.com/puppetlabs/puppetlabs-firewall.git"
  symlinks:
    "keystone": "#{source_dir}"
